{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "\n",
    "import sqlalchemy\n",
    "from sqlalchemy.ext.automap import automap_base\n",
    "from sqlalchemy.orm import Session\n",
    "from sqlalchemy import create_engine, func, inspect\n",
    "\n",
    "from flask import Flask, jsonify\n",
    "import datetime as dt\n",
    "\n",
    "\n",
    "# Relative Date\n",
    "\n",
    "\n",
    "#################################################\n",
    "# Database Setup\n",
    "#################################################\n",
    "engine = create_engine(\"sqlite:///Resources/hawaii.sqlite\", connect_args={'check_same_thread': False}, echo=True)\n",
    "# reflect an existing database into a new model\n",
    "Base = automap_base()\n",
    "# reflect the tables\n",
    "Base.prepare(engine, reflect=True)\n",
    "\n",
    "# Save reference to the table\n",
    "Measurement = Base.classes.measurement\n",
    "Station = Base.classes.station\n",
    "# Create our session (link) from Python to the DB\n",
    "session = Session(engine)\n",
    "\n",
    "#################################################\n",
    "# Flask Setup\n",
    "#################################################\n",
    "app = Flask(__name__)\n",
    "\n",
    "\n",
    "#################################################\n",
    "# Flask Routes\n",
    "#################################################\n",
    "\n",
    "@app.route(\"/\")\n",
    "def welcome():\n",
    "    \"\"\"List all available api routes.\"\"\"\n",
    "    return\"\"\"<html>\n",
    "    <h1>List of all available Honolulu, HI API routes</h1>\n",
    "    <ul>\n",
    "    <br>\n",
    "    <li>\n",
    "    Return a list of precipitations from last year:\n",
    "    <br>\n",
    "    <a href=\"/api/v1.0/precipitation\">/api/v1.0/precipitation</a>\n",
    "    </li>\n",
    "    <br>\n",
    "    <li>\n",
    "    Return a JSON list of stations from the dataset: \n",
    "    <br>\n",
    "   <a href=\"/api/v1.0/stations\">/api/v1.0/stations</a>\n",
    "   </li>\n",
    "    <br>\n",
    "    <li>\n",
    "    Return a JSON list of Temperature Observations (tobs) for the previous year:\n",
    "    <br>\n",
    "    <a href=\"/api/v1.0/tobs\">/api/v1.0/tobs</a>\n",
    "    </li>\n",
    "    <br>\n",
    "    <li>\n",
    "    Return a JSON list of tmin, tmax, tavg for the dates greater than or equal to the date provided:\n",
    "    <br>Replace &ltstart&gt with a date in Year-Month-Day format.\n",
    "    <br>\n",
    "    <a href=\"/api/v1.0/2017-01-01\">/api/v1.0/2017-01-01</a>\n",
    "    </li>\n",
    "    <br>\n",
    "    <li>\n",
    "    Return a JSON list of tmin, tmax, tavg for the dates in range of start date and end date inclusive:\n",
    "    <br>\n",
    "    Replace &ltstart&gt and &ltend&gt with a date in Year-Month-Day format. \n",
    "    <br>\n",
    "    <br>\n",
    "    <a href=\"/api/v1.0/2017-01-01/2017-01-07\">/api/v1.0/2017-01-01/2017-01-07</a>\n",
    "    </li>\n",
    "    <br>\n",
    "    </ul>\n",
    "    </html>\n",
    "    \"\"\"\n",
    "\n",
    "\n",
    "@app.route(\"/api/v1.0/precipitation\")\n",
    "def precipitation():\n",
    "    # Docstring \n",
    "    \"\"\"Return a list of precipitations from last year\"\"\"\n",
    "    # Design a query to retrieve the last 12 months of precipitation data and plot the results\n",
    "    max_date = session.query(Measurement.date).order_by(Measurement.date.desc()).first()\n",
    "\n",
    "    # Get the first element of the tuple\n",
    "    max_date = max_date[0]\n",
    "\n",
    "    # Calculate the date 1 year ago from today\n",
    "    # The days are equal 366 so that the first day of the year is included\n",
    "    year_ago = dt.datetime.strptime(max_date, \"%Y-%m-%d\") - dt.timedelta(days=366)\n",
    "    \n",
    "    # Perform a query to retrieve the data and precipitation scores\n",
    "    results_precipitation = session.query(Measurement.date, Measurement.prcp).filter(Measurement.date >= year_ago).all()\n",
    "\n",
    "    # Convert list of tuples into normal list\n",
    "    precipitation_dict = dict(results_precipitation)\n",
    "\n",
    "    return jsonify(precipitation_dict)\n",
    "\n",
    "@app.route(\"/api/v1.0/stations\")\n",
    "def stations(): \n",
    "    # Docstring\n",
    "    \"\"\"Return a JSON list of stations from the dataset.\"\"\"\n",
    "    # Query stations\n",
    "    results_stations =  session.query(Measurement.station).group_by(Measurement.station).all()\n",
    "\n",
    "    # Convert list of tuples into normal list\n",
    "    stations_list = list(np.ravel(results_stations))\n",
    "\n",
    "    return jsonify(stations_list)\n",
    "\n",
    "@app.route(\"/api/v1.0/tobs\")\n",
    "def tobs(): \n",
    "    # Docstring\n",
    "    \"\"\"Return a JSON list of Temperature Observations (tobs) for the previous year.\"\"\"\n",
    "\n",
    "    # Design a query to retrieve the last 12 months of precipitation data and plot the results\n",
    "    max_date = session.query(Measurement.date).order_by(Measurement.date.desc()).first()\n",
    "\n",
    "    # Get the first element of the tuple\n",
    "    max_date = max_date[0]\n",
    "\n",
    "    # Calculate the date 1 year ago from today\n",
    "    # The days are equal 366 so that the first day of the year is included\n",
    "    year_ago = dt.datetime.strptime(max_date, \"%Y-%m-%d\") - dt.timedelta(days=366)\n",
    "    # Query tobs\n",
    "    results_tobs = session.query(Measurement.date, Measurement.tobs).filter(Measurement.date >= year_ago).all()\n",
    "\n",
    "    # Convert list of tuples into normal list\n",
    "    tobs_list = list(results_tobs)\n",
    "\n",
    "    return jsonify(tobs_list)\n",
    "\n",
    "\n",
    "\n",
    "@app.route(\"/api/v1.0/<start>\")\n",
    "def start(start=None):\n",
    "\n",
    "    # Docstring\n",
    "    \"\"\"Return a JSON list of tmin, tmax, tavg for the dates greater than or equal to the date provided\"\"\"\n",
    "\n",
    "    from_start = session.query(Measurement.date, func.min(Measurement.tobs), func.avg(Measurement.tobs), func.max(Measurement.tobs)).filter(Measurement.date >= start).group_by(Measurement.date).all()\n",
    "    from_start_list=list(from_start)\n",
    "    return jsonify(from_start_list)\n",
    "\n",
    "    \n",
    "\n",
    "@app.route(\"/api/v1.0/<start>/<end>\")\n",
    "def start_end(start=None, end=None):\n",
    "    # Docstring\n",
    "    \"\"\"Return a JSON list of tmin, tmax, tavg for the dates in range of start date and end date inclusive\"\"\"\n",
    "    \n",
    "    between_dates = session.query(Measurement.date, func.min(Measurement.tobs), func.avg(Measurement.tobs), func.max(Measurement.tobs)).filter(Measurement.date >= start).filter(Measurement.date <= end).group_by(Measurement.date).all()\n",
    "    between_dates_list=list(between_dates)\n",
    "    return jsonify(between_dates_list)\n",
    "\n",
    "\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    app.run(debug=True)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
